/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekakhir;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.awt.Font;


/**
 *
 * @author Muhammad Fajri
 */
public class TicTacToe extends javax.swing.JFrame {
   
    private boolean isPlayerTurn = true; 
    private boolean vsComputer = false; 
    private int turnCounter = 0; 
    private boolean gameStarted = false;
    private enum Difficulty {
    EASY, MEDIUM, HARD
}
    private Difficulty currentDifficulty = Difficulty.HARD;

    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Klik1 = new javax.swing.JButton();
        Klik2 = new javax.swing.JButton();
        Klik3 = new javax.swing.JButton();
        Klik4 = new javax.swing.JButton();
        Klik5 = new javax.swing.JButton();
        Klik6 = new javax.swing.JButton();
        Klik7 = new javax.swing.JButton();
        Klik8 = new javax.swing.JButton();
        Klik9 = new javax.swing.JButton();
        player = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        komputer = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(940, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        Klik1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Klik1ActionPerformed(evt);
            }
        });
        jPanel1.add(Klik1);

        Klik2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Klik2ActionPerformed(evt);
            }
        });
        jPanel1.add(Klik2);

        Klik3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Klik3ActionPerformed(evt);
            }
        });
        jPanel1.add(Klik3);

        Klik4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Klik4ActionPerformed(evt);
            }
        });
        jPanel1.add(Klik4);

        Klik5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Klik5ActionPerformed(evt);
            }
        });
        jPanel1.add(Klik5);

        Klik6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Klik6ActionPerformed(evt);
            }
        });
        jPanel1.add(Klik6);

        Klik7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Klik7ActionPerformed(evt);
            }
        });
        jPanel1.add(Klik7);

        Klik8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Klik8ActionPerformed(evt);
            }
        });
        jPanel1.add(Klik8);

        Klik9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Klik9ActionPerformed(evt);
            }
        });
        jPanel1.add(Klik9);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 460, 380));

        player.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekakhir/Player.png"))); // NOI18N
        player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerActionPerformed(evt);
            }
        });
        getContentPane().add(player, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 150, 50));

        Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekakhir/Kembali.png"))); // NOI18N
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 150, 50));

        komputer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekakhir/Computer.png"))); // NOI18N
        komputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komputerActionPerformed(evt);
            }
        });
        getContentPane().add(komputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 150, 50));

        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekakhir/reset.png"))); // NOI18N
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekakhir/TicTacToe.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(940, 650));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerActionPerformed
        vsComputer = false; // Menandakan pemain memilih bermain dengan teman
        resetGame(); // Reset permainan
        gameStarted = true; // Menandakan permainan sudah dimulai
        JOptionPane.showMessageDialog(this, "Anda memilih 'Bermain dengan Teman'.");
    }//GEN-LAST:event_playerActionPerformed

private void disableButtons() {
    // Menonaktifkan tombol-tombol setelah pertandingan selesai
    Klik1.setEnabled(false);
    Klik2.setEnabled(false);
    Klik3.setEnabled(false);
    Klik4.setEnabled(false);
    Klik5.setEnabled(false);
    Klik6.setEnabled(false);
    Klik7.setEnabled(false);
    Klik8.setEnabled(false);
    Klik9.setEnabled(false);
}    
 private void checkGameStarted() {
    if (!gameStarted) {
        JOptionPane.showMessageDialog(this, "Silakan pilih apakah akan bermain dengan teman atau komputer terlebih dahulu.");
    }
}

private void handleButtonClick(javax.swing.JButton button, int index) {
    checkGameStarted(); // Cek jika game belum dimulai
    
    if (!button.getText().isEmpty() || !gameStarted) return; // Jika tombol sudah terisi atau game belum dimulai, abaikan
    
    Font font = new Font("Arial", Font.BOLD, 60); // Ukuran font yang lebih besar
    button.setFont(font);
    
    if (turnCounter % 2 == 0) {
        button.setText("O"); // Giliran lingkaran
        button.setForeground(Color.BLUE);
    } else {
        button.setText("X"); // Giliran silang
        button.setForeground(Color.RED);
    }

    turnCounter++;

    // Cek kondisi menang
    if (checkWin()) {
        String winner = turnCounter % 2 == 0 ? "Player 2 (X)" : "Player 1 (O)";
        JOptionPane.showMessageDialog(this, winner + " Menang!");
        saveScore(winner); // Simpan skor jika ada pemenang
        disableButtons(); // Menonaktifkan tombol setelah pertandingan selesai
        return;
    }

    // Cek seri
    if (turnCounter == 9) {
        JOptionPane.showMessageDialog(this, "Pertandingan Seri!");
        resetGame(); // Reset permainan jika seri
        return;
    }

    // Jika melawan komputer dan giliran komputer
    if (vsComputer && turnCounter % 2 == 1) {
        computerMove(); // Gerakan komputer
    }
}

private boolean checkWin() {
    int[][] winPositions = {
        {0, 1, 2}, {3, 4, 5}, {6, 7, 8}, // Horizontal
        {0, 3, 6}, {1, 4, 7}, {2, 5, 8}, // Vertical
        {0, 4, 8}, {2, 4, 6}             // Diagonal
    };

    String[] values = new String[]{
        Klik1.getText(), Klik2.getText(), Klik3.getText(),
        Klik4.getText(), Klik5.getText(), Klik6.getText(),
        Klik7.getText(), Klik8.getText(), Klik9.getText()
    };

    for (int[] pos : winPositions) {
        if (!values[pos[0]].isEmpty() &&
            values[pos[0]].equals(values[pos[1]]) &&
            values[pos[1]].equals(values[pos[2]])) {
            return true;
        }
    }

    return false;
}

private void saveScore(String winner) {
    // Simpan skor berdasarkan pemenang
    if (winner.equals("Player 1 (O)")) {
        // Simpan skor Player 1
    } else if (winner.equals("Player 2 (X)")) {
        // Simpan skor Player 2
    }
}
private void computerMove() {
    int move = findBestMove(); // Mencari langkah terbaik untuk komputer
    makeMove(move, "X");

    // Cek kemenangan setelah langkah komputer
    if (checkWin()) {
        JOptionPane.showMessageDialog(this, "Komputer Menang!");
        saveScore("Komputer Menang");
        disableButtons(); // Menonaktifkan tombol setelah permainan selesai
    }
}

private int findBestMove() {
    int bestVal = -1000;
    int bestMove = -1;

    // Cek langkah kemenangan komputer terlebih dahulu
    bestMove = findWinningMove("X");
    if (bestMove != -1) return bestMove;

    // Cek jika pemain dapat menang, blokir langkah tersebut
    bestMove = findWinningMove("O");
    if (bestMove != -1) return bestMove;

    // Jika tidak ada langkah kemenangan, pilih langkah terbaik menggunakan minimax
    // Cari langkah terbaik menggunakan minimax
    for (int i = 0; i < 9; i++) {
        if (isCellEmpty(i)) {
            makeMove(i, "X"); // Simulasikan langkah komputer
            int moveVal = minimax(0, false); // Dapatkan nilai dari langkah tersebut
            undoMove(i); // Kembalikan langkah

            // Pilih langkah yang memberikan nilai terbaik
            if (moveVal > bestVal) {
                bestMove = i;
                bestVal = moveVal;
            }
        }
    }
    return bestMove;
}

private int findWinningMove(String symbol) {
    // Mencari langkah yang dapat memenangkan permainan untuk simbol yang diberikan
    javax.swing.JButton[] buttons = {Klik1, Klik2, Klik3, Klik4, Klik5, Klik6, Klik7, Klik8, Klik9};
    for (int i = 0; i < 9; i++) {
        if (isCellEmpty(i)) {
            makeMove(i, symbol); // Simulasi langkah
            if (checkWin()) {
                undoMove(i); // Kembalikan langkah jika menang
                return i; // Kembalikan indeks langkah yang menang
            }
            undoMove(i); // Kembalikan langkah jika tidak menang
        }
    }
    return -1; // Tidak ada langkah yang bisa menang
}

private boolean isCellEmpty(int index) {
    // Cek apakah tombol pada posisi index kosong
    javax.swing.JButton[] buttons = {Klik1, Klik2, Klik3, Klik4, Klik5, Klik6, Klik7, Klik8, Klik9};
    return buttons[index].getText().isEmpty();
}

private void makeMove(int index, String symbol) {
    javax.swing.JButton[] buttons = {Klik1, Klik2, Klik3, Klik4, Klik5, Klik6, Klik7, Klik8, Klik9};

    // Menentukan ukuran font yang lebih besar
    Font font = new Font("Arial", Font.BOLD, 60); // Ukuran font 60, jenis Arial, dan tebal

    buttons[index].setText(symbol);
    buttons[index].setFont(font); // Menetapkan font ke tombol
    buttons[index].setForeground(symbol.equals("X") ? Color.RED : Color.BLUE); // Menentukan warna simbol
    turnCounter++;
}

private void undoMove(int index) {
    // Membatalkan langkah yang telah dibuat
    javax.swing.JButton[] buttons = {Klik1, Klik2, Klik3, Klik4, Klik5, Klik6, Klik7, Klik8, Klik9};
    buttons[index].setText("");
    turnCounter--;
}

private int minimax(int depth, boolean isMaximizingPlayer) {
    // Minimax untuk menilai langkah terbaik
    int score = evaluateBoard();
    
    // Jika komputer menang
    if (score == 10) return score;

    // Jika pemain menang
    if (score == -10) return score;

    // Jika papan penuh (seri)
    if (turnCounter == 9) return 0;

    // Jika giliran komputer (maximizing player)
    if (isMaximizingPlayer) {
        int best = -1000;

        // Periksa setiap langkah yang mungkin untuk komputer
        for (int i = 0; i < 9; i++) {
            if (isCellEmpty(i)) {
                makeMove(i, "X"); // Komputer bergerak
                best = Math.max(best, minimax(depth + 1, false));
                undoMove(i);
            }
        }
        return best;
    } else { // Jika giliran pemain (minimizing player)
        int best = 1000;

        // Periksa setiap langkah yang mungkin untuk pemain
        for (int i = 0; i < 9; i++) {
            if (isCellEmpty(i)) {
                makeMove(i, "O"); // Pemain bergerak
                best = Math.min(best, minimax(depth + 1, true));
                undoMove(i);
            }
        }
        return best;
    }
}

private int evaluateBoard() {
    // Cek apakah ada pemenang dan nilai berdasarkan pemenang
    if (checkWin()) {
        return turnCounter % 2 == 0 ? -10 : 10; // Komputer menang = 10, Pemain menang = -10
    }
    return 0; // Jika tidak ada pemenang
}




private void resetGame() {
   Klik1.setText(""); // Reset semua tombol
    Klik2.setText("");
    Klik3.setText("");
    Klik4.setText("");
    Klik5.setText("");
    Klik6.setText("");
    Klik7.setText("");
    Klik8.setText("");
    Klik9.setText("");
    turnCounter = 0; // Reset hitungan giliran
    gameStarted = false; // Menandakan permainan belum dimulai
    isPlayerTurn = true; // Giliran pemain pertama
    
    Klik1.setEnabled(true);
    Klik2.setEnabled(true);
    Klik3.setEnabled(true);
    Klik4.setEnabled(true);
    Klik5.setEnabled(true);
    Klik6.setEnabled(true);
    Klik7.setEnabled(true);
    Klik8.setEnabled(true);
    Klik9.setEnabled(true);
}



    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        this.dispose();
        
        MenuUtama menuUtama = new MenuUtama();
        menuUtama.setVisible(true);
    }//GEN-LAST:event_KembaliActionPerformed

    private void komputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komputerActionPerformed
        vsComputer = true; // Menandakan pemain memilih bermain dengan komputer
        resetGame(); // Reset permainan
        gameStarted = true; // Menandakan permainan sudah dimulai
        JOptionPane.showMessageDialog(this, "Anda memilih 'Bermain dengan Komputer'.");
    }//GEN-LAST:event_komputerActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
            resetGame();
    }//GEN-LAST:event_ResetActionPerformed

    private void Klik1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Klik1ActionPerformed
        // TODO add your handling code here:
        handleButtonClick(Klik1, 0);
    }//GEN-LAST:event_Klik1ActionPerformed

    private void Klik2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Klik2ActionPerformed
        // TODO add your handling code here:
        handleButtonClick(Klik2, 1);
    }//GEN-LAST:event_Klik2ActionPerformed

    private void Klik3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Klik3ActionPerformed
        // TODO add your handling code here:
        handleButtonClick(Klik3, 2);
    }//GEN-LAST:event_Klik3ActionPerformed

    private void Klik4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Klik4ActionPerformed
        // TODO add your handling code here:
        handleButtonClick(Klik4, 3);
    }//GEN-LAST:event_Klik4ActionPerformed

    private void Klik5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Klik5ActionPerformed
        // TODO add your handling code here:
        handleButtonClick(Klik5, 4);
    }//GEN-LAST:event_Klik5ActionPerformed

    private void Klik6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Klik6ActionPerformed
        // TODO add your handling code here:
        handleButtonClick(Klik6, 5);
    }//GEN-LAST:event_Klik6ActionPerformed

    private void Klik7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Klik7ActionPerformed
        // TODO add your handling code here:
        handleButtonClick(Klik7, 6);
    }//GEN-LAST:event_Klik7ActionPerformed

    private void Klik8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Klik8ActionPerformed
        // TODO add your handling code here:
        handleButtonClick(Klik8, 7);
    }//GEN-LAST:event_Klik8ActionPerformed

    private void Klik9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Klik9ActionPerformed
        // TODO add your handling code here:
        handleButtonClick(Klik9, 8);
    }//GEN-LAST:event_Klik9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kembali;
    private javax.swing.JButton Klik1;
    private javax.swing.JButton Klik2;
    private javax.swing.JButton Klik3;
    private javax.swing.JButton Klik4;
    private javax.swing.JButton Klik5;
    private javax.swing.JButton Klik6;
    private javax.swing.JButton Klik7;
    private javax.swing.JButton Klik8;
    private javax.swing.JButton Klik9;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton komputer;
    private javax.swing.JButton player;
    // End of variables declaration//GEN-END:variables
}
